# Generated by Django 2.0.1 on 2018-02-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180202_0027'),
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscrubers',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
