# Generated by Django 2.0.1 on 2018-02-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_subscriber_subscrubers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscrubers',
        ),
    ]
