# Generated by Django 2.0.1 on 2018-02-06 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('levelOfTraining', models.CharField(choices=[('low', 'Низикий'), ('medium', 'Средний'), ('high', 'Высокий'), ('veryhigh', 'Очень высокий')], default='medium', max_length=20)),
                ('organizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizators.Organizator')),
            ],
        ),
    ]
