# Generated by Django 2.0.1 on 2018-01-30 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180130_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 30, 12, 23, 2, 311901, tzinfo=utc)),
        ),
    ]
