# Generated by Django 2.0.1 on 2018-01-30 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='levelOfTraining',
            field=models.CharField(choices=[('low', 'Низикий'), ('medium', 'Средний'), ('high', 'Высокий'), ('veryhigh', 'Очень высокий')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
