# Generated by Django 2.0.1 on 2018-02-01 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20180130_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organizator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='organizators.Organizator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
