# Generated by Django 2.0.1 on 2018-02-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0001_initial'),
        ('project', '0006_remove_project_organizator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='organizator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizators.Organizator'),
            preserve_default=False,
        ),
    ]
